# Generated by Django 5.2.8 on 2025-11-15 15:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=2048, verbose_name="Post Title")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Is Published?"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Published"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
